//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Address { get; set; }
        public string Gender { get; set; }
        public string Country { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public string CoveragePlan { get; set; }
        public Nullable<int> NetPrice { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
    }
}
