//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoveragePlan
    {
        public string CoveragePlan1 { get; set; }
        public Nullable<System.DateTime> EligibilityDateFrom { get; set; }
        public Nullable<System.DateTime> EligibilityDateTo { get; set; }
        public string EligibilityCountry { get; set; }
        public int PlanID { get; set; }
    }
}
