//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TakeHomeDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RateChart
    {
        public string CoveragePlan { get; set; }
        public string Gender { get; set; }
        public string Age { get; set; }
        public Nullable<int> NetPrice { get; set; }
        public int RateChartID { get; set; }
    }
}
